parameters:
#    qnoow_landing.example.class: Qnoow\LandingBundle\Example

services:
#    qnoow_landing.example:
#        class: %qnoow_landing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
